'use server';

import bcrypt from 'bcryptjs';
import fs from 'node:fs/promises';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { requireAdmin } from '@/lib/auth/session';
import { saveUpload, uploadPath } from '@/lib/upload';

const s = (fd: FormData, k: string) => String(fd.get(k) || '').trim();
const n = (fd: FormData, k: string) => { const v=s(fd,k); return v ? Number(v) : null; };
const day = (fd: FormData, k: string) => { const v=n(fd,k); return v ? Math.min(Math.max(Math.trunc(v),1),31) : null; };
const d = (fd: FormData, k: string) => new Date(`${s(fd,k)}T00:00:00`);
function back(path: string, lang: string) { revalidatePath(path); redirect(`${path}?lang=${lang}`); }
const chargeStatuses = ['OPEN','PARTIAL','PAID','LATE','OVERDUE','VOID'];
function uploadName(pathOrUrl: string) {
  const m = pathOrUrl.match(/^\/api\/uploads\/([^/?#]+)/);
  return m ? decodeURIComponent(m[1]) : null;
}
async function deleteUploadIfLocal(pathOrUrl?: string | null) {
  const name = pathOrUrl ? uploadName(pathOrUrl) : null;
  if (!name) return;
  try { await fs.unlink(uploadPath(name)); } catch {}
}
async function refreshChargeStatus(chargeId: string) {
  const charge = await prisma.rentCharge.findUnique({ where: { id: chargeId }, include: { payments: true } });
  if (!charge || charge.status === 'VOID') return;
  const paid = charge.payments.reduce((sum, p) => sum + Number(p.amount), 0);
  const due = Number(charge.amount) + Number(charge.lateFee);
  const status = paid >= due ? 'PAID' : paid > 0 ? 'PARTIAL' : charge.dueDate < new Date() ? 'OVERDUE' : 'OPEN';
  await prisma.rentCharge.update({ where: { id: chargeId }, data: { status: status as any } });
}

export async function createProperty(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.property.create({ data: { nickname:s(fd,'nickname')||null, address1:s(fd,'address1'), address2:s(fd,'address2')||null, city:s(fd,'city'), state:s(fd,'state')||'FL', zip:s(fd,'zip'), bedrooms:n(fd,'bedrooms'), bathrooms:n(fd,'bathrooms'), monthlyRent:n(fd,'monthlyRent'), rentDueDay:day(fd,'rentDueDay'), deposit:n(fd,'deposit'), marketValue:n(fd,'marketValue'), latitude:n(fd,'latitude'), longitude:n(fd,'longitude'), status:s(fd,'status') as any, notes:s(fd,'notes')||null }}); back('/landlord/properties',lang); }
export async function deleteProperty(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.property.delete({ where:{ id:s(fd,'id') }}); back('/landlord/properties',lang); }

export async function createTenant(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const email=s(fd,'email').toLowerCase() || null; const password=s(fd,'password'); let userId: string | undefined; if (email && password) { const user = await prisma.user.upsert({ where:{ email }, update:{ name:`${s(fd,'firstName')} ${s(fd,'lastName')}`, role:'TENANT', passwordHash: await bcrypt.hash(password,12) }, create:{ email, name:`${s(fd,'firstName')} ${s(fd,'lastName')}`, role:'TENANT', passwordHash: await bcrypt.hash(password,12) }}); userId=user.id; } await prisma.tenant.create({ data:{ userId, firstName:s(fd,'firstName'), lastName:s(fd,'lastName'), email, phone:s(fd,'phone')||null, rentDueDay:day(fd,'rentDueDay'), smsOptIn:s(fd,'smsOptIn')==='on', emergencyName:s(fd,'emergencyName')||null, emergencyPhone:s(fd,'emergencyPhone')||null, notes:s(fd,'notes')||null }}); back('/landlord/tenants',lang); }
export async function deleteTenant(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.tenant.delete({ where:{ id:s(fd,'id') }}); back('/landlord/tenants',lang); }

export async function createLease(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const property=await prisma.property.findUnique({where:{id:s(fd,'propertyId')}}); const lease = await prisma.lease.create({ data:{ propertyId:s(fd,'propertyId'), templateId:s(fd,'templateId')||'florida-long-term-v1', status:s(fd,'status') as any, startDate:d(fd,'startDate'), endDate:d(fd,'endDate'), monthlyRent:n(fd,'monthlyRent') || 0, rentDueDay:day(fd,'rentDueDay')||property?.rentDueDay||null, securityDeposit:n(fd,'securityDeposit'), petFeeMonthly:n(fd,'petFeeMonthly'), repairThreshold:n(fd,'repairThreshold') }}); const tenantIds=fd.getAll('tenantId').map(String).filter(Boolean); for (const [idx,tenantId] of tenantIds.entries()) await prisma.leaseTenant.create({ data:{ leaseId:lease.id, tenantId, primary:idx===0 }}); back('/landlord/leases',lang); }
export async function deleteLease(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.lease.delete({ where:{ id:s(fd,'id') }}); back('/landlord/leases',lang); }

export async function createCharge(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.rentCharge.create({ data:{ leaseId:s(fd,'leaseId'), dueDate:d(fd,'dueDate'), description:s(fd,'description')||'Monthly rent', amount:n(fd,'amount')||0, lateFee:n(fd,'lateFee')||0, status:s(fd,'status') as any }}); back('/landlord/rent',lang); }
export async function deleteCharge(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.rentCharge.delete({ where:{ id:s(fd,'id') }}); back('/landlord/rent',lang); }
export async function createPayment(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const chargeId=s(fd,'chargeId'); await prisma.rentPayment.create({ data:{ chargeId, paidAt:d(fd,'paidAt'), amount:n(fd,'amount')||0, method:s(fd,'method')||'manual', reference:s(fd,'reference')||null, notes:s(fd,'notes')||null }}); await refreshChargeStatus(chargeId); back('/landlord/rent',lang); }

export async function createMaintenance(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.maintenanceRequest.create({ data:{ propertyId:s(fd,'propertyId'), tenantId:s(fd,'tenantId')||null, title:s(fd,'title'), description:s(fd,'description'), priority:s(fd,'priority')||'normal', cost:n(fd,'cost'), status:s(fd,'status') as any }}); back('/landlord/maintenance',lang); }
export async function deleteMaintenance(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.maintenanceRequest.delete({ where:{ id:s(fd,'id') }}); back('/landlord/maintenance',lang); }

export async function createDocument(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.document.create({ data:{ title:s(fd,'title'), kind:s(fd,'kind'), path:s(fd,'path'), propertyId:s(fd,'propertyId')||null, tenantId:s(fd,'tenantId')||null, leaseId:s(fd,'leaseId')||null }}); back('/landlord/documents',lang); }
export async function deleteDocument(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const doc=await prisma.document.findUnique({where:{id:s(fd,'id')}}); await prisma.document.delete({ where:{ id:s(fd,'id') }}); await deleteUploadIfLocal(doc?.path); back('/landlord/documents',lang); }

export async function createTemplate(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.leaseTemplate.create({ data:{ name:s(fd,'name'), version:s(fd,'version')||'1.0', jurisdiction:s(fd,'jurisdiction')||'Florida', bodyMarkdown:s(fd,'bodyMarkdown'), active:s(fd,'active')==='on' }}); back('/landlord/lease-templates',lang); }
export async function deleteTemplate(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.leaseTemplate.delete({ where:{ id:s(fd,'id') }}); back('/landlord/lease-templates',lang); }

export async function updateProperty(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.property.update({ where:{id:s(fd,'id')}, data:{ nickname:s(fd,'nickname')||null, address1:s(fd,'address1'), address2:s(fd,'address2')||null, city:s(fd,'city'), state:s(fd,'state')||'FL', zip:s(fd,'zip'), status:s(fd,'status') as any, monthlyRent:n(fd,'monthlyRent'), rentDueDay:day(fd,'rentDueDay'), deposit:n(fd,'deposit'), marketValue:n(fd,'marketValue'), bedrooms:n(fd,'bedrooms'), bathrooms:n(fd,'bathrooms'), latitude:n(fd,'latitude'), longitude:n(fd,'longitude'), notes:s(fd,'notes')||null }}); back(`/landlord/properties/${s(fd,'id')}`,lang); }
export async function updateTenant(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.tenant.update({ where:{id:s(fd,'id')}, data:{ firstName:s(fd,'firstName'), lastName:s(fd,'lastName'), email:s(fd,'email').toLowerCase()||null, phone:s(fd,'phone')||null, rentDueDay:day(fd,'rentDueDay'), smsOptIn:s(fd,'smsOptIn')==='on', emergencyName:s(fd,'emergencyName')||null, emergencyPhone:s(fd,'emergencyPhone')||null, notes:s(fd,'notes')||null }}); back('/landlord/tenants',lang); }
export async function updateLease(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const id=s(fd,'id'); await prisma.lease.update({ where:{id}, data:{ propertyId:s(fd,'propertyId'), templateId:s(fd,'templateId')||null, status:s(fd,'status') as any, startDate:d(fd,'startDate'), endDate:d(fd,'endDate'), monthlyRent:n(fd,'monthlyRent')||0, rentDueDay:day(fd,'rentDueDay'), securityDeposit:n(fd,'securityDeposit'), petFeeMonthly:n(fd,'petFeeMonthly'), repairThreshold:n(fd,'repairThreshold') }}); const tenantIds=fd.getAll('tenantId').map(String).filter(Boolean); await prisma.leaseTenant.deleteMany({where:{leaseId:id}}); for (const [idx,tenantId] of tenantIds.entries()) await prisma.leaseTenant.create({data:{leaseId:id,tenantId,primary:idx===0}}); back(`/landlord/leases/${id}`,lang); }
export async function updateCharge(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const status=chargeStatuses.includes(s(fd,'status'))?s(fd,'status'):'OPEN'; await prisma.rentCharge.update({ where:{id:s(fd,'id')}, data:{ dueDate:d(fd,'dueDate'), description:s(fd,'description')||'Monthly rent', amount:n(fd,'amount')||0, lateFee:n(fd,'lateFee')||0, status:status as any }}); back(`/landlord/rent/${s(fd,'id')}`,lang); }
export async function updateMaintenance(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.maintenanceRequest.update({ where:{id:s(fd,'id')}, data:{ title:s(fd,'title'), description:s(fd,'description'), priority:s(fd,'priority')||'normal', cost:n(fd,'cost'), status:s(fd,'status') as any }}); back('/landlord/maintenance',lang); }
export async function updateDocument(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const id=s(fd,'id'); const old=await prisma.document.findUnique({where:{id}}); const file=fd.get('file'); let path=s(fd,'path'); if(file instanceof File && file.size>0){ path=await saveUpload(file); await deleteUploadIfLocal(old?.path); } await prisma.document.update({ where:{id}, data:{ title:s(fd,'title'), kind:s(fd,'kind'), path, propertyId:s(fd,'propertyId')||null, tenantId:s(fd,'tenantId')||null, leaseId:s(fd,'leaseId')||null }}); back(`/landlord/documents/${id}`,lang); }
export async function updateTemplate(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; await prisma.leaseTemplate.update({ where:{id:s(fd,'id')}, data:{ name:s(fd,'name'), version:s(fd,'version')||'1.0', jurisdiction:s(fd,'jurisdiction')||'Florida', bodyMarkdown:s(fd,'bodyMarkdown'), active:s(fd,'active')==='on' }}); back(`/landlord/lease-templates/${s(fd,'id')}`,lang); }

export async function generateMonthlyCharges(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const month=s(fd,'month') || new Date().toISOString().slice(0,7); const monthStart = new Date(`${month}-01T00:00:00`); const monthEnd = new Date(monthStart); monthEnd.setMonth(monthEnd.getMonth()+1); const leases = await prisma.lease.findMany({ where:{ status:{in:['ACTIVE','SIGNED']} }, include:{property:true} }); let created=0; for (const lease of leases) { const dueDay=Math.min(lease.rentDueDay||lease.property.rentDueDay||1, new Date(monthStart.getFullYear(), monthStart.getMonth()+1, 0).getDate()); const dueDate=new Date(monthStart); dueDate.setDate(dueDay); const existing=await prisma.rentCharge.findFirst({where:{leaseId:lease.id,dueDate:{gte:monthStart,lt:monthEnd},description:{contains:`Monthly rent ${month}`}}}); if(!existing){ await prisma.rentCharge.create({data:{leaseId:lease.id,dueDate,description:`Monthly rent ${month}`,amount:lease.monthlyRent,status:'OPEN'}}); created++; } } revalidatePath('/landlord/rent'); redirect(`/landlord/rent?lang=${lang}&generated=${created}`); }
export async function applyRentAutomation(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const fee=n(fd,'lateFee')||0; const today=new Date(); const rows=await prisma.rentCharge.findMany({where:{status:{in:['OPEN','PARTIAL','LATE','OVERDUE']},dueDate:{lt:today}}}); for (const row of rows) { const paid=await prisma.rentPayment.aggregate({where:{chargeId:row.id},_sum:{amount:true}}); const totalPaid=Number(paid._sum.amount||0); const totalDue=Number(row.amount)+Number(row.lateFee); if(totalPaid < totalDue){ await prisma.rentCharge.update({where:{id:row.id},data:{status:'OVERDUE',lateFee: fee>Number(row.lateFee)?fee:row.lateFee}}); } } revalidatePath('/landlord/rent'); redirect(`/landlord/rent?lang=${lang}&overdue=${rows.length}`); }
export async function uploadAdminDocument(fd: FormData) { await requireAdmin(); const lang=s(fd,'lang')||'en'; const file=fd.get('file'); let path=s(fd,'path'); if(file instanceof File && file.size>0){ path=await saveUpload(file); } if(!path) back('/landlord/documents', lang); await prisma.document.create({ data:{ title:s(fd,'title') || (file instanceof File ? file.name : 'Document'), kind:s(fd,'kind')||'upload', path, propertyId:s(fd,'propertyId')||null, tenantId:s(fd,'tenantId')||null, leaseId:s(fd,'leaseId')||null }}); back('/landlord/documents', lang); }
